### PR TITLE
Refresh toolkit

### PR DESCRIPTION
**Pull request by MGatner**
* Updates PHPStan to `^1.0`
* Fixes a few issues with integration workflows
* Drop PHP 7.3 support

### CODE REVIEW

**Comment by kenjis** [comment]
This PR is a bit out of dated. I will update.

**Comment by kenjis** [comment]
The following test fails on PHP 8.0, but I can't reproduce on my local.

```
There was 1 failure:

1) CachePoolTest::testHasItemReturnsFalseWhenDeferredItemIsExpired
Failed asserting that true is false.

/home/runner/work/cache/cache/vendor/cache/integration-tests/src/CachePoolTest.php:872
```
https://github.com/codeigniter4/cache/runs/6718288349?check_suite_focus=true

**Comment by MGatner** [comment]
Odd! The tests used to pass on Actions. I just looked at the code and it seems fine? Maybe it is a timezone issue?

**Comment by MGatner** [comment]
README badges will need to be updated as well.

**Comment by kenjis** [comment]
The GitHub auth error occurs many times on this repository. 

> Could not authenticate against github.com  

Probably the repositories is the cause.
https://github.com/codeigniter4/cache/blob/b965e7f51a1575a1fce49035886c7fbdaf87190a/composer.json#L54-L59

**Comment by kenjis** [comment]
> README badges will need to be updated as well.

Updated.

**Comment by MGatner** [comment]
> Probably the repositories is the cause. 

Most definitely. I've been removing this from all my projects and I no longer get the Auth issue. This should switch to `codeigniter4/framework: ^4.1` and drop the repositories key.

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by MGatner** [comment]
Thanks for your help on this one! I let that sit stale way too long 😅

**Pull request merged**
