### PR TITLE
chore: fix workflow on section

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #16
See https://github.com/codeigniter4/.github/issues/14

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I think workflow failure was unrelated, rerunning.

**Review by MGatner — APPROVED** [review]

**Comment by kenjis** [comment]
It seems the job was cancelled. But there is no reason.
Re-run failed jobs.

```
2023-09-12T06:22:51.4019726Z --2023-09-12 06:22:51--  https://download.oracle.com/otn_software/linux/instantclient/185000/oracle-instantclient18.5-sqlplus-18.5.0.0.0-3.x86_64.rpm
2023-09-12T06:22:51.4074873Z Resolving download.oracle.com (download.oracle.com)... 23.62.160.87
2023-09-12T06:22:51.4128175Z Connecting to download.oracle.com (download.oracle.com)|23.62.160.87|:443... connected.
2023-09-12T06:22:51.5854333Z HTTP request sent, awaiting response... 200 OK
2023-09-12T06:22:51.5855586Z Length: 709112 (692K) [application/x-redhat-package-manager]
2023-09-12T06:22:51.5857902Z Saving to: ‘oracle-instantclient18.5-sqlplus-18.5.0.0.0-3.x86_64.rpm’
2023-09-12T06:22:51.5864037Z 
2023-09-12T06:22:51.5924054Z      0K .......... .......... .......... .......... ..........  7% 8.30M 0s
2023-09-12T06:22:51.5972953Z     50K .......... .......... .......... .......... .......... 14% 8.68M 0s
2023-09-12T06:22:51.6026215Z    100K .......... .......... .......... .......... .......... 21% 9.21M 0s
2023-09-12T06:22:51.6066558Z    150K .......... .......... .......... .......... .......... 28% 12.1M 0s
2023-09-12T06:22:51.6074642Z    200K .......... .......... .......... .......... .......... 36% 60.0M 0s
2023-09-12T06:22:51.6105971Z    250K .......... .......... .......... .......... .......... 43% 15.7M 0s
2023-09-12T06:22:51.6109240Z    300K .......... .......... .......... .......... .......... 50%  132M 0s
2023-09-12T06:22:51.6129432Z    350K .......... .......... .......... .......... .......... 57% 24.4M 0s
2023-09-12T06:22:51.6133343Z    400K .......... .......... .......... .......... .......... 64%  123M 0s
2023-09-12T06:22:51.6142380Z    450K .......... .......... .......... .......... .......... 72% 53.6M 0s
2023-09-12T06:22:51.6151711Z    500K .......... .......... .......... .......... .......... 79% 52.4M 0s
2023-09-12T06:22:51.6160694Z    550K .......... .......... .......... .......... .......... 86% 54.5M 0s
2023-09-12T06:22:51.6170823Z    600K .......... .......... .......... .......... .......... 93% 50.0M 0s
2023-09-12T06:22:51.6173789Z    650K .......... .......... .......... .......... ..        100%  126M=0.03s
2023-09-12T06:22:51.6173970Z 
2023-09-12T06:22:51.6176976Z 2023-09-12 06:22:51 (21.4 MB/s) - ‘oracle-instantclient18.5-sqlplus-18.5.0.0.0-3.x86_64.rpm’ saved [709112/709112]
2023-09-12T06:22:51.6178663Z 
2023-09-12T06:24:34.6267194Z oracle-instantclient18.5-basic_18.5.0.0.0-4_amd64.deb generated
2023-09-12T06:24:34.7551623Z ##[error]The operation was canceled.
```

**Comment by kenjis** [comment]
@MGatner It seems this repository has no database test.
Is it not necessary to run the tests on all databases supported by CI4?

**Comment by MGatner** [comment]
> Is it not necessary to run the tests on all databases supported by CI4?

It is not necessary. These implementations are agnostic to the underlying drivers, and those are thoroughly tested in the framework itself.

**Comment by kenjis** [comment]
Okay, I will create a new PHPUnit workflow for packages with no database.

https://github.com/codeigniter4/.github/pull/15

**Pull request merged**
